import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'kn' | 'ml' | 'bn' | 'gu' | 'mr' | 'pa';

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languages: { code: Language; name: string; nativeName: string }[];
}

const languages = [
  { code: 'en' as Language, name: 'English', nativeName: 'English' },
  { code: 'hi' as Language, name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'ta' as Language, name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te' as Language, name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'kn' as Language, name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml' as Language, name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'bn' as Language, name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'gu' as Language, name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'mr' as Language, name: 'Marathi', nativeName: 'मराठी' },
  { code: 'pa' as Language, name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' }
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'welcome': 'Welcome',
    'login': 'Login',
    'logout': 'Logout',
    'dashboard': 'Dashboard',
    'profile': 'Profile',
    'settings': 'Settings',
    'help': 'Help',
    'chat': 'Chat Assistant',
    'voice_assistant': 'Voice Assistant',
    'language': 'Language',
    'accessibility': 'Accessibility',
    'save': 'Save',
    'cancel': 'Cancel',
    'close': 'Close',
    'continue': 'Continue',
    'back': 'Back',
    'next': 'Next',
    'submit': 'Submit',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Information',
    'edit': 'Edit',
    'delete': 'Delete',
    'view': 'View',
    'download': 'Download',
    'upload': 'Upload',
    'search': 'Search',
    
    // Landing Page
    'sai_title': 'SAI Talent Assessment Platform',
    'sai_subtitle': 'Democratizing Sports Talent Discovery Through AI',
    'sai_description': 'Advanced AI-powered platform for comprehensive fitness assessment and talent identification, designed to revolutionize sports development across India.',
    'get_started': 'Get Started',
    'learn_more': 'Learn More',
    'ai_video_analysis': 'AI-Powered Video Analysis',
    'ai_video_analysis_desc': 'Advanced computer vision analyzes your performance in real-time with professional accuracy',
    'on_device_processing': 'On-Device Processing',
    'on_device_processing_desc': 'Lightning-fast analysis without internet dependency, ensuring privacy and instant feedback',
    'cheat_detection': 'Cheat Detection',
    'cheat_detection_desc': 'Sophisticated algorithms ensure fair assessment by detecting anomalies and manipulations',
    'performance_benchmarking': 'Performance Benchmarking',
    'performance_benchmarking_desc': 'Compare your results against age and gender-based national standards and benchmarks',
    'gamified_experience': 'Gamified Experience',
    'gamified_experience_desc': 'Earn badges, climb leaderboards, and track your progress with engaging visual feedback',
    'trusted_by_sai': 'Trusted by Sports Authority of India',
    'contact_us': 'Contact Us',
    'about': 'About',
    'privacy_policy': 'Privacy Policy',
    'terms_of_service': 'Terms of Service',
    
    // Navigation
    'home': 'Home',
    'tests': 'Tests',
    'results': 'Results',
    'recommendations': 'Recommendations',
    'athletes': 'Athletes',
    'coaches': 'Coaches',
    'test_center': 'Test Center',
    'analytics': 'Analytics',
    'reports': 'Reports',
    'mental_training': 'Mental Training',
    'social': 'Social',
    'achievements': 'Achievements',
    'leaderboard': 'Leaderboard',
    
    // Auth
    'sign_in': 'Sign In',
    'sign_up': 'Sign Up',
    'email': 'Email',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'forgot_password': 'Forgot Password?',
    'remember_me': 'Remember me',
    'create_account': 'Create Account',
    'already_have_account': 'Already have an account?',
    'dont_have_account': "Don't have an account?",
    'choose_role': 'Choose Your Role',
    'athlete_role': 'Athlete',
    'coach_role': 'Coach/Scout',
    'official_role': 'SAI Official',
    'athlete_desc': 'Take fitness tests and get personalized recommendations',
    'coach_desc': 'Evaluate and manage athlete performance',
    'official_desc': 'Monitor and analyze talent across regions',
    
    // Profile Setup
    'complete_profile': 'Complete Your Profile',
    'personal_info': 'Personal Information',
    'name': 'Full Name',
    'age': 'Age',
    'gender': 'Gender',
    'height': 'Height (cm)',
    'weight': 'Weight (kg)',
    'location': 'Location',
    'phone': 'Phone Number',
    'specialization': 'Specialization',
    'experience': 'Years of Experience',
    'certifications': 'Certifications',
    'parent_consent': 'Parent/Guardian Consent',
    'parent_name': 'Parent/Guardian Name',
    'parent_email': 'Parent/Guardian Email',
    'parent_phone': 'Parent/Guardian Phone',
    'relationship': 'Relationship',
    'consent_given': 'I give consent for my child to participate',
    'male': 'Male',
    'female': 'Female',
    'other': 'Other',
    'prefer_not_to_say': 'Prefer not to say',
    
    // Tests
    'fitness_tests': 'Fitness Tests',
    'start_test': 'Start Test',
    'test_results': 'Test Results',
    'height_test': 'Height Measurement',
    'weight_test': 'Weight Measurement',
    'flexibility_test': 'Flexibility Test',
    'vertical_jump': 'Vertical Jump',
    'broad_jump': 'Broad Jump',
    'medicine_ball_throw': 'Medicine Ball Throw',
    'sprint_30m': '30m Sprint',
    'shuttle_run': 'Shuttle Run',
    'sit_ups': 'Sit-ups',
    'endurance_run': 'Endurance Run',
    'test_instructions': 'Test Instructions',
    'test_preparation': 'Test Preparation',
    'test_execution': 'Test Execution',
    'test_completed': 'Test Completed',
    'view_results': 'View Results',
    'retake_test': 'Retake Test',
    'ai_analysis': 'AI Analysis',
    'performance_score': 'Performance Score',
    'recommendations_based_on_test': 'Recommendations based on your test',
    
    // Sport Recommendations
    'sport_recommendations': 'Sport Recommendations',
    'recommended_sports': 'Recommended Sports for You',
    'athletics': 'Athletics',
    'weightlifting': 'Weightlifting',
    'gymnastics': 'Gymnastics',
    'swimming': 'Swimming',
    'basketball': 'Basketball',
    'football': 'Football',
    'cricket': 'Cricket',
    'badminton': 'Badminton',
    'tennis': 'Tennis',
    'hockey': 'Hockey',
    'boxing': 'Boxing',
    'wrestling': 'Wrestling',
    'volleyball': 'Volleyball',
    'kabaddi': 'Kabaddi',
    'archery': 'Archery',
    
    // Dashboard
    'welcome_back': 'Welcome back',
    'overall_score': 'Overall Score',
    'recent_tests': 'Recent Tests',
    'progress_overview': 'Progress Overview',
    'upcoming_tests': 'Upcoming Tests',
    'achievements_unlocked': 'Achievements Unlocked',
    'performance_trends': 'Performance Trends',
    'quick_actions': 'Quick Actions',
    'take_new_test': 'Take New Test',
    'view_progress': 'View Progress',
    'update_profile': 'Update Profile',
    'schedule_test': 'Schedule Test',
    
    // Coach Dashboard
    'coach_dashboard': 'Coach Dashboard',
    'total_athletes': 'Total Athletes',
    'average_score': 'Average Score',
    'notifications': 'Notifications',
    'add_athlete': 'Add Athlete',
    'overview': 'Overview',
    'roster': 'Roster',
    'training_plans': 'Training Plans',
    'messaging': 'Messaging',
    'personal_training': 'Personal Training',
    'analytics': 'Analytics',
    'video_analysis': 'Video AI',
    'mind_gym': 'Mind Gym',
    'community': 'Community',
    'wearables': 'Wearables',
    'recent_activity': 'Recent Activity',
    'recent_messages': 'Recent Messages',
    'watchlist': 'Watchlist',
    'completed_tests': 'Completed {count} tests',
    'injury_risk': 'Injury Risk',
    'mental_wellness': 'Mental Wellness',
    'mood': 'Mood',
    'stress': 'Stress',
    'sleep_quality': 'Sleep Quality',
    'motivation': 'Motivation',
    'view_profile': 'View Profile',
    'send_message': 'Send Message',
    'create_plan': 'Create Plan',
    'schedule_session': 'Schedule Session',
    'athlete_name': 'Athlete Name',
    'position': 'Position',
    'join_date': 'Join Date',
    'last_active': 'Last Active',
    'tests_completed': 'Tests Completed',
    'improvement': 'Improvement',
    'training_plan': 'Training Plan',
    'duration': 'Duration',
    'difficulty': 'Difficulty',
    'completion_rate': 'Completion Rate',
    'assigned_athletes': 'Assigned Athletes',
    'exercises': 'Exercises',
    'athletes': 'Athletes',
    'new': 'New',
    'ago': 'ago',
    'hours': 'hours',
    'days': 'days',
    'low': 'Low',
    'medium': 'Medium',
    'high': 'High',
    'beginner': 'Beginner',
    'intermediate': 'Intermediate', 
    'advanced': 'Advanced',
    'sprinter': 'Sprinter',
    'long_jump': 'Long Jump',
    'endurance': 'Endurance',
    'weightlifter': 'Weightlifter',
    'manage_athletes_progress': 'Manage your athletes and track their progress',
    'search_athletes': 'Search athletes...',
    'filter_by_sport': 'Filter by Sport',
    'export_data': 'Export Data',
    'filter': 'Filter',
    'tests': 'Tests',
    'todays_wearable_data': 'Today\'s Wearable Data',
    'steps': 'Steps',
    'heart_rate': 'HR',
    'calories': 'Calories',
    'sleep': 'Sleep',
    'risk': 'RISK',
    'improvement': 'Improvement',
    'last_active': 'Last active',
    'mood': 'Mood',
    'stress': 'Stress',
    'sleep_quality': 'Sleep',
    'motivation': 'Motivation',
    'view_profile': 'View Profile',
    'message': 'Message',
    'personal_plan': 'Personal Plan',
    'schedule': 'Schedule',
    'training_plans': 'Training Plans',
    'create_manage_training_programs': 'Create and manage custom training programs',
    'create_new_plan': 'Create New Plan',
    'completion_rate': 'Completion Rate',
    'edit_plan': 'Edit Plan',
    'assign': 'Assign',
    'athlete_communication_center': 'Athlete Communication Center',
    'direct_communication_athletes': 'Direct communication with your athletes',
    'new_group_message': 'New Group Message',
    'conversations': 'Conversations',
    'select_athlete': 'Select Athlete',
    'select_athlete_messaging': 'Select an athlete to start messaging',
    'hours': 'hours',
    'hour': 'hour',
    'ago': 'ago',
    'type_message': 'Type your message...',
    'schedule_session': 'Schedule Session',
    'send_plan': 'Send Plan',
    'video_call': 'Video Call',
    'personal_training_guidance': 'Personal Training & Guidance',
    'one_on_one_coaching': 'One-on-one coaching and personalized training plans',
    'create_personal_plan': 'Create Personal Plan',
    'active_personal_plans': 'Active Personal Plans',
    'focus': 'Focus',
    'speed_agility': 'Speed & Agility',
    'active': 'Active',
    'view_plan': 'View Plan',
    'modify': 'Modify',
    'scheduled_sessions': 'Scheduled Sessions',
    'sprint_technique_session': 'Sprint Technique Session',
    'today': 'Today',
    'with': 'with',
    'acceleration_phase': 'Acceleration phase',
    'join_session': 'Join Session',
    'reschedule': 'Reschedule',
    'endurance_assessment': 'Endurance Assessment',
    'tomorrow': 'Tomorrow',
    'vo2_max_testing': 'VO2 Max testing',
    'view_details': 'View Details',
    'technique_review': 'Technique Review',
    'wed': 'Wed',
    'long_jump_form_analysis': 'Long jump form analysis',
    'coaching_resources_guidance': 'Coaching Resources & Guidance Tools',
    'video_analysis_tools': 'Video Analysis Tools',
    'record_analyze_movements': 'Record and analyze athlete movements',
    'training_templates': 'Training Templates',
    'prebuilt_workout_templates': 'Pre-built workout and drill templates',
    'mental_training': 'Mental Training',
    'psychology_motivation_tools': 'Psychology and motivation tools',
    'goal_setting': 'Goal Setting',
    'smart_goal_frameworks': 'SMART goal frameworks',
    'progress_tracking': 'Progress Tracking',
    'performance_metrics_dashboard': 'Performance metrics dashboard',
    'injury_prevention': 'Injury Prevention',
    'risk_assessment_tools': 'Risk assessment tools',
    'advanced_analytics_insights': 'Advanced Analytics & Performance Insights',
    'comprehensive_data_analysis': 'Comprehensive data analysis and talent scouting insights',
    'team_performance_trends': 'Team Performance Trends',
    'performance_chart': 'Performance Chart',
    'six_month_comparison': '6-month comparison',
    'avg_improvement': 'Avg Improvement',
    'training_adherence': 'Training Adherence',
    'injury_rate': 'Injury Rate',
    
    // Chatbot
    'chat_welcome': 'Hello! I\'m your SAI fitness assistant. How can I help you today?',
    'chat_placeholder': 'Ask me anything about fitness tests...',
    'send': 'Send',
    'typing': 'Typing...',
    
    // Voice Assistant
    'voice_listening': 'Listening...',
    'voice_speak': 'Speak now',
    'voice_not_supported': 'Voice recognition not supported in this browser',
    'voice_activation': 'Voice Activation',
    'enable_voice': 'Enable Voice Commands',
    
    // Accessibility
    'high_contrast': 'High Contrast',
    'large_text': 'Large Text',
    'screen_reader': 'Screen Reader Mode',
    'keyboard_navigation': 'Keyboard Navigation',
    'voice_commands': 'Voice Commands',
    'accessibility_options': 'Accessibility Options',
    'reduce_motion': 'Reduce Motion',
    'focus_indicators': 'Enhanced Focus Indicators',
    
    // Errors and Messages
    'camera_access_required': 'Camera access is required for fitness tests',
    'location_access_required': 'Location access is required for verification',
    'microphone_access_required': 'Microphone access is required for voice commands',
    'test_failed': 'Test failed to complete',
    'test_successful': 'Test completed successfully',
    'profile_updated': 'Profile updated successfully',
    'settings_saved': 'Settings saved successfully',
    'invalid_credentials': 'Invalid email or password',
    'network_error': 'Network connection error',
    'permission_denied': 'Permission denied',
    'feature_not_available': 'Feature not available in this browser',
    
    // Status and States
    'online': 'Online',
    'offline': 'Offline',
    'connecting': 'Connecting...',
    'connected': 'Connected',
    'disconnected': 'Disconnected',
    'active': 'Active',
    'inactive': 'Inactive',
    'enabled': 'Enabled',
    'disabled': 'Disabled',
    'available': 'Available',
    'unavailable': 'Unavailable',
    'in_progress': 'In Progress',
    'completed': 'Completed',
    'pending': 'Pending',
    'approved': 'Approved',
    'rejected': 'Rejected'
  },
  hi: {
    // Common
    'welcome': 'स्वागत है',
    'login': 'लॉगिन',
    'logout': 'लॉगआउट',
    'dashboard': 'डैशबोर्ड',
    'profile': 'प्रोफाइल',
    'settings': 'सेटिंग्स',
    'help': 'सहायता',
    'chat': 'चैट सहायक',
    'voice_assistant': 'आवाज सहायक',
    'language': 'भाषा',
    'accessibility': 'पहुंच',
    'save': 'सेव करें',
    'cancel': 'रद्द करें',
    'close': 'बंद करें',
    'continue': 'जारी रखें',
    'back': 'वापस',
    'next': 'अगला',
    'submit': 'जमा करें',
    'loading': 'लोड हो रहा है...',
    'error': 'त्रुटि',
    'success': 'सफल',
    'warning': 'चेतावनी',
    'info': 'जानकारी',
    'edit': 'संपादित करें',
    'delete': 'हटाएं',
    'view': 'देखें',
    'download': 'डाउनलोड',
    'upload': 'अपलोड',
    'search': 'खोजें',
    
    // Landing Page
    'sai_title': 'SAI प्रतिभा मूल्यांकन प्लेटफॉर्म',
    'sai_subtitle': 'AI के माध्यम से खेल प्रतिभा खोज का लोकतंत्रीकरण',
    'sai_description': 'व्यापक फिटनेस मूल्यांकन और प्रतिभा पहचान के लिए उन्नत AI-संचालित प्लेटफॉर्म, भारत भर में खेल विकास में क्रांति लाने के लिए डिज़ाइन किया गया।',
    'get_started': 'शुरू करें',
    'learn_more': 'और जानें',
    'ai_video_analysis': 'AI-संचालित वीडियो विश्लेषण',
    'ai_video_analysis_desc': 'उन्नत कंप्यूटर विजन आपके प्रदर्शन का पेशेवर सटीकता के साथ रीयल-टाइम विश्लेषण करता है',
    'on_device_processing': 'डिवाइस पर प्रोसेसिंग',
    'on_device_processing_desc': 'इंटरनेट निर्भरता के बिना तेज़ विश्लेषण, गोपनीयता और तत्काल फीडबैक सुनिश्चित करता है',
    'cheat_detection': 'धोखाधड़ी का पता लगाना',
    'cheat_detection_desc': 'परिष्कृत एल्गोरिदम विसंगतियों और हेराफेरी का पता लगाकर निष्पक्ष मूल्यांकन सुनिश्चित करते हैं',
    'performance_benchmarking': 'प्रदर्शन बेंचमार्किंग',
    'performance_benchmarking_desc': 'अपने परिणामों की तुलना आयु और लिंग-आधारित राष्ट्रीय मानकों और बेंचमार्क से करें',
    'gamified_experience': 'गेमिफाइड अनुभव',
    'gamified_experience_desc': 'बैज अर्जित करें, लीडरबोर्ड पर चढ़ें, और आकर्षक दृश्य फीडबैक के साथ अपनी प्रगति को ट्रैक करें',
    'trusted_by_sai': 'भारतीय खेल प्राधिकरण द्वारा भरोसेमंद',
    'contact_us': 'संपर्क करें',
    'about': 'के बारे में',
    'privacy_policy': 'गोपनीयता नीति',
    'terms_of_service': 'सेवा की शर्त���ं',
    
    // Navigation
    'home': 'मुख्य',
    'tests': 'परीक्षण',
    'results': 'परिणाम',
    'recommendations': 'सिफारिशें',
    'athletes': 'खिलाड़ी',
    'coaches': 'कोच',
    'test_center': 'टेस्ट सेंटर',
    'analytics': 'विश्लेषण',
    'reports': 'रिपोर्ट',
    'mental_training': 'मानसिक प्रशिक्षण',
    'social': 'सामाजिक',
    'achievements': 'उपलब्धियां',
    'leaderboard': 'लीडरबोर्ड',
    
    // Auth
    'sign_in': 'साइन इन',
    'sign_up': 'साइन अप',
    'email': 'ईमेल',
    'password': 'पासवर्ड',
    'confirm_password': 'पासवर्ड की पुष्टि करें',
    'forgot_password': 'पासवर्ड भूल गए?',
    'remember_me': 'मुझे याद रखें',
    'create_account': 'खाता बनाएं',
    'already_have_account': 'पहले से खाता है?',
    'dont_have_account': 'खाता नहीं है?',
    'choose_role': 'अपनी भूमिका चुनें',
    'athlete_role': 'खिलाड़ी',
    'coach_role': 'कोच/स्काउट',
    'official_role': 'SAI अधिकारी',
    'athlete_desc': 'फिटनेस टेस्ट लें और व्यक्तिगत सिफारिशें प्राप्त करें',
    'coach_desc': 'खिलाड़ी के प्रदर्शन का मूल्यांकन और प्रबंधन करें',
    'official_desc': 'क्षेत्रों में प्रतिभा की निगरानी और विश्लेषण करें',
    
    // Profile Setup
    'complete_profile': 'अपनी प्रोफाइल पूरी करें',
    'personal_info': 'व्यक्तिगत जानकारी',
    'name': 'पूरा नाम',
    'age': 'उम्र',
    'gender': 'लिंग',
    'height': 'लंबाई (सेमी)',
    'weight': 'वजन (किग्रा)',
    'location': 'स्थान',
    'phone': 'फोन नंबर',
    'specialization': 'विशेषज्ञता',
    'experience': 'अनुभव के वर्ष',
    'certifications': 'प्रमाणपत्र',
    'parent_consent': 'माता-पिता/अभिभावक की सहमति',
    'parent_name': 'माता-पिता/अभिभावक का नाम',
    'parent_email': 'माता-पिता/अभिभावक का ईमेल',
    'parent_phone': 'माता-पिता/अभिभावक का फोन',
    'relationship': 'रिश्ता',
    'consent_given': 'मैं अपने बच्चे की भागीदारी के लिए सहमति देता हूं',
    'male': 'पुरुष',
    'female': 'महिला',
    'other': 'अन्य',
    'prefer_not_to_say': 'नहीं बताना चाहते',
    
    // Tests
    'fitness_tests': 'फिटनेस टेस्ट',
    'start_test': 'टेस्ट शुरू करें',
    'test_results': 'टेस्ट परिणाम',
    'height_test': 'लंबाई मापना',
    'weight_test': 'वजन मापना',
    'flexibility_test': 'लचीलापन टेस्ट',
    'vertical_jump': 'ऊर्ध्वाधर कूद',
    'broad_jump': 'चौड़ी कूद',
    'medicine_ball_throw': 'मेडिसिन बॉल थ्रो',
    'sprint_30m': '30मी दौड़',
    'shuttle_run': 'शटल रन',
    'sit_ups': 'सिट-अप्स',
    'endurance_run': 'सहनशीलता दौड़',
    'test_instructions': 'टेस्ट निर्देश',
    'test_preparation': 'टेस्ट की तैयारी',
    'test_execution': 'टेस्ट निष्पादन',
    'test_completed': 'टेस्ट पूरा',
    'view_results': 'परिणाम देखें',
    'retake_test': 'टेस्ट दोबारा लें',
    'ai_analysis': 'AI विश्लेषण',
    'performance_score': 'प्रदर्शन स्कोर',
    'recommendations_based_on_test': 'आपके टेस्ट के आधार पर सिफारिशें',
    
    // Sport Recommendations
    'sport_recommendations': 'खेल सिफारिशें',
    'recommended_sports': 'आपके लिए सुझाए गए खेल',
    'athletics': 'एथलेटिक्स',
    'weightlifting': 'भारोत्तोलन',
    'gymnastics': 'जिम्नास्टिक',
    'swimming': 'तैराकी',
    'basketball': 'बास्केटबॉल',
    'football': 'फुटबॉल',
    'cricket': 'क्रिकेट',
    'badminton': 'बैडमिंटन',
    'tennis': 'टेनिस',
    'hockey': 'हॉकी',
    'boxing': 'मुक्केबाजी',
    'wrestling': 'कुश्ती',
    'volleyball': 'वॉलीबॉल',
    'kabaddi': 'कबड्डी',
    'archery': 'तीरंदाजी',
    
    // Dashboard
    'welcome_back': 'वापस स्वागत है',
    'overall_score': 'कुल स्कोर',
    'recent_tests': 'हाल के टेस्ट',
    'progress_overview': 'प्रगति अवलोकन',
    'upcoming_tests': 'आगामी टेस्ट',
    'achievements_unlocked': 'अनलॉक की गई उपलब्धियां',
    'performance_trends': 'प्रदर्शन रुझान',
    'quick_actions': 'त्वरित क्रियाएं',
    'take_new_test': 'नया टेस्ट लें',
    'view_progress': 'प्रगति देखें',
    'update_profile': 'प्रोफाइल अपडेट करें',
    'schedule_test': 'टेस्ट शेड्यूल करें',
    
    // Coach Dashboard
    'coach_dashboard': 'कोच डैशबोर्ड',
    'total_athletes': 'कुल खिलाड़ी',
    'average_score': 'औसत स्कोर',
    'notifications': 'सूचनाएं',
    'add_athlete': 'खिलाड़ी जोड़ें',
    'overview': 'अवलोकन',
    'roster': 'सूची',
    'training_plans': 'प्रशिक्षण योजनाएं',
    'messaging': 'संदेश',
    'personal_training': 'व्यक्तिगत प्रशिक्षण',
    'analytics': 'विश्लेषण',
    'video_analysis': 'वीडियो AI',
    'mind_gym': 'मानसिक जिम',
    'community': 'समुदाय',
    'wearables': 'पहनने योग्य डिवाइस',
    'recent_activity': 'हाल की गतिविधि',
    'recent_messages': 'हाल के संदेश',
    'watchlist': 'निगरानी सूची',
    'completed_tests': '{count} टेस्ट पूरे किए',
    'injury_risk': 'चोट का जोखिम',
    'mental_wellness': 'मानसिक स्वास्थ्य',
    'mood': 'मूड',
    'stress': 'तनाव',
    'sleep_quality': 'नींद की गुणवत्ता',
    'motivation': 'प्रेरणा',
    'view_profile': 'प्रोफाइल देखें',
    'send_message': 'संदेश भेजें',
    'create_plan': 'योजना बनाएं',
    'schedule_session': 'सत्र शेड्यूल करें',
    'athlete_name': 'खिलाड़ी का नाम',
    'position': 'स्थिति',
    'join_date': 'शामिल होने की तारीख',
    'last_active': 'अंतिम सक्रिय',
    'tests_completed': 'टेस्ट पूरे किए',
    'improvement': 'सुधार',
    'training_plan': 'प्रशिक्षण योजना',
    'duration': 'अवधि',
    'difficulty': 'कठिनाई',
    'completion_rate': 'पूर्णता दर',
    'assigned_athletes': 'निर्दिष्ट खिलाड़ी',
    'exercises': 'व्यायाम',
    'athletes': 'खिलाड़ी',
    'new': 'नया',
    'ago': 'पहले',
    'hours': 'घंटे',
    'days': 'दिन',
    'low': 'कम',
    'medium': 'मध्यम',
    'high': 'उच्च',
    'beginner': 'शुरुआती',
    'intermediate': 'मध्यम',
    'advanced': 'उन्नत',
    'sprinter': 'धावक',
    'long_jump': 'लंबी कूद',
    'endurance': 'सहनशीलता',
    'weightlifter': 'भारोत्तोलक',
    'manage_athletes_progress': 'अपने खिलाड़ियों का प्रबंधन करें और उनकी प्रगति को ट्रैक करें',
    'search_athletes': 'खिलाड़ी खोजें...',
    'filter_by_sport': 'खेल के अनुसार फ़िल्टर करें',
    'export_data': 'डेटा निर्यात करें',
    'filter': 'फ़िल्टर',
    'tests': 'टेस्ट',
    'todays_wearable_data': 'आज का पहनने योग्य डेटा',
    'steps': 'कदम',
    'heart_rate': 'HR',
    'calories': 'कैलोरी',
    'sleep': 'नींद',
    'risk': 'जोखिम',
    'improvement': 'सुधार',
    'last_active': 'अंतिम सक्रिय',
    'mood': 'मूड',
    'stress': 'तनाव',
    'sleep_quality': 'नींद',
    'motivation': 'प्रेरणा',
    'view_profile': 'प्रोफ़ाइल देखें',
    'message': 'संदेश',
    'personal_plan': 'व्यक्तिगत योजना',
    'schedule': 'अनुसूची',
    'training_plans': 'प्रशिक्षण योजनाएं',
    'create_manage_training_programs': 'कस्टम प्रशिक्षण कार्यक्रम बनाएं और प्रबंधित करें',
    'create_new_plan': 'नई योजना बनाएं',
    'completion_rate': 'पूर्णता दर',
    'edit_plan': 'योजना संपादित करें',
    'assign': 'असाइन करें',
    'athlete_communication_center': 'खिलाड़ी संचार केंद्र',
    'direct_communication_athletes': 'अपने खिलाड़ियों के साथ प्रत्यक्ष संचार',
    'new_group_message': 'नया समूह संदेश',
    'conversations': 'बातचीत',
    'select_athlete': 'खिलाड़ी चुनें',
    'select_athlete_messaging': 'मैसेजिंग शुरू करने के लिए एक खिलाड़ी चुनें',
    'hours': 'घंटे',
    'hour': 'घंटा',
    'ago': 'पहले',
    'type_message': 'अपना संदेश टाइप करें...',
    'schedule_session': 'सत्र निर्धारित करें',
    'send_plan': 'योजना भेजें',
    'video_call': 'वीडियो कॉल',
    'personal_training_guidance': 'व्यक्तिगत प्रशिक्षण और मार्गदर्शन',
    'one_on_one_coaching': 'एक-पर-एक कोचिंग और व्यक्तिगत प्रशिक्षण योजनाएं',
    'create_personal_plan': 'व्यक्तिगत योजना बनाएं',
    'active_personal_plans': 'सक्रिय व्यक्तिगत योजनाएं',
    'focus': 'फोकस',
    'speed_agility': 'गति और चपलता',
    'active': 'सक्रिय',
    'view_plan': 'योजना देखें',
    'modify': 'संशोधित करें',
    'scheduled_sessions': 'निर्धारित सत्र',
    'sprint_technique_session': 'स्प्रिंट तकनीक सत्र',
    'today': 'आज',
    'with': 'के साथ',
    'acceleration_phase': 'त्वरण चरण',
    'join_session': 'सत्र में शामिल हों',
    'reschedule': 'पुनर्निर्धारित करें',
    'endurance_assessment': 'सहनशीलता मूल्यांकन',
    'tomorrow': 'कल',
    'vo2_max_testing': 'VO2 मैक्स परीक्षण',
    'view_details': 'विवरण देखें',
    'technique_review': 'तकनीक समीक्षा',
    'wed': 'बुध',
    'long_jump_form_analysis': 'लंबी कूद फॉर्म विश्लेषण',
    'coaching_resources_guidance': 'कोचिंग संसाधन और मार्गदर्शन उपकरण',
    'video_analysis_tools': 'वीडियो विश्लेषण उपकरण',
    'record_analyze_movements': 'खिलाड़ी की गतिविधियों को रिकॉर्ड और विश्लेषित करें',
    'training_templates': 'प्रशिक्षण टेम्प्लेट',
    'prebuilt_workout_templates': 'पूर्व-निर्मित वर्कआउट और ड्रिल टेम्प्लेट',
    'mental_training': 'मानसिक प्रशिक्षण',
    'psychology_motivation_tools': 'मनोविज्ञान और प्रेरणा उपकरण',
    'goal_setting': 'लक्ष्य निर्धारण',
    'smart_goal_frameworks': 'SMART लक्ष्य ढांचे',
    'progress_tracking': 'प्रगति ट्रैकिंग',
    'performance_metrics_dashboard': 'प्रदर्शन मेट्रिक्स डैशबोर्ड',
    'injury_prevention': 'चोट की रोकथाम',
    'risk_assessment_tools': 'जोखिम मूल्यांकन उपकरण',
    'advanced_analytics_insights': 'उन्नत विश्लेषण और प्रदर्शन अंतर्दृष्टि',
    'comprehensive_data_analysis': 'व्यापक डेटा विश्लेषण और प्रतिभा स्काउटिंग अंतर्दृष्टि',
    'team_performance_trends': 'टीम प्रदर्शन रुझान',
    'performance_chart': 'प्रदर्शन चार्ट',
    'six_month_comparison': '6-महीने की तुलना',
    'avg_improvement': 'औसत सुधार',
    'training_adherence': 'प्रशिक्षण पालन',
    'injury_rate': 'चोट दर',
    
    // Chatbot
    'chat_welcome': 'नमस्ते! मैं आपका SAI फिटनेस सहायक हूं। आज मैं आपकी कैसे सहायता कर सकता हूं?',
    'chat_placeholder': 'फिटनेस टेस्ट के बारे में कुछ भी पूछें...',
    'send': 'भेजें',
    'typing': 'टाइप कर रहा है...',
    
    // Voice Assistant
    'voice_listening': 'सुन रहा हूं...',
    'voice_speak': 'अब बोलें',
    'voice_not_supported': 'इस ब्राउज़र में आवाज पहचान समर्थित नहीं है',
    'voice_activation': 'आवाज सक्रियण',
    'enable_voice': 'आवाज कमांड सक्षम करें',
    
    // Accessibility
    'high_contrast': 'उच्च कंट्रास्ट',
    'large_text': 'बड़ा टेक्स्ट',
    'screen_reader': 'स्क्रीन रीडर मोड',
    'keyboard_navigation': 'कीबोर्ड नेवीगेशन',
    'voice_commands': 'आवाज कमांड',
    'accessibility_options': 'पहुंच विकल्प',
    'reduce_motion': 'गति कम करें',
    'focus_indicators': 'बेहतर फोकस संकेतक',
    
    // Errors and Messages
    'camera_access_required': 'फिटनेस टेस्ट के लिए कैमरा एक्सेस आवश्यक है',
    'location_access_required': 'सत्यापन के लिए स्थान एक्सेस आवश्यक है',
    'microphone_access_required': 'आवाज कमांड के लिए माइक्रोफोन एक्सेस आवश्यक है',
    'test_failed': 'टेस्ट पूरा करने में असफल',
    'test_successful': 'टेस्ट सफलतापूर्वक पूरा हुआ',
    'profile_updated': 'प्रोफाइल सफलतापूर्वक अपडेट हुई',
    'settings_saved': 'सेटिंग्स सफलतापूर्वक सेव हुईं',
    'invalid_credentials': 'अमान्य ईमेल या पासवर्ड',
    'network_error': 'नेटवर्क कनेक्शन त्रुटि',
    'permission_denied': 'अनुमति अस्वीकृत',
    'feature_not_available': 'यह सुविधा इस ब्राउज़र में उपलब्ध नहीं है',
    
    // Status and States
    'online': 'ऑनलाइन',
    'offline': 'ऑफलाइन',
    'connecting': 'कनेक्ट हो रहा है...',
    'connected': 'जुड़ा हुआ',
    'disconnected': 'डिस्कनेक्ट हुआ',
    'active': 'सक्रिय',
    'inactive': 'निष्क्रिय',
    'enabled': 'सक्षम',
    'disabled': 'निष्क्रिय',
    'available': 'उपलब्ध',
    'unavailable': 'अनुपलब्ध',
    'in_progress': 'प्रगति में',
    'completed': 'पूर्ण',
    'pending': 'लंबित',
    'approved': 'अनुमोदित',
    'rejected': 'अस्वीकृत'
  },
  ta: {
    // Common
    'welcome': 'வரவேற்கிறோம்',
    'login': 'உள்நுழைய',
    'logout': 'வெளியேறு',
    'dashboard': 'டாஷ்போர்டு',
    'profile': 'சுயவிவரம்',
    'settings': 'அமைப்புகள்',
    'help': 'உதவி',
    'chat': 'அரட்டை உதவியாளர்',
    'voice_assistant': 'குரல் உதவியாளர்',
    'language': 'மொழி',
    'accessibility': 'அணுகல்',
    
    // Tests
    'fitness_tests': 'உடல்நலப் பரிசோதனைகள்',
    'start_test': 'சோதனையைத் தொடங்கு',
    'sport_recommendations': 'விளையாட்டு பரிந்துரைகள்'
  },
  te: {
    // Common
    'welcome': 'స్వాగతం',
    'login': 'లాగిన్',
    'logout': 'లాగ్అవుట్',
    'dashboard': 'డ్యాష్‌బోర్డ్',
    'profile': 'ప్రొఫైల్',
    'settings': 'సెట్టింగులు',
    'help': 'సహాయం',
    'chat': 'చాట్ అసిస్టెంట్',
    'voice_assistant': 'వాయిస్ అసిస్టెంట్',
    'language': 'భాష',
    'accessibility': 'యాక్సెసిబిలిటీ'
  },
  kn: {
    // Common
    'welcome': 'ಸ್ವಾಗತ',
    'login': 'ಲಾಗಿನ್',
    'logout': 'ಲಾಗ್ಔಟ್',
    'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'profile': 'ಪ್ರೊಫೈಲ್',
    'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'help': 'ಸಹಾಯ',
    'chat': 'ಚಾಟ್ ಸಹಾಯಕ',
    'voice_assistant': 'ಧ್ವನಿ ಸಹಾಯಕ',
    'language': 'ಭಾಷೆ',
    'accessibility': 'ಪ್ರವೇಶಸಾಧ್ಯತೆ'
  },
  ml: {
    // Common
    'welcome': 'സ്വാഗതം',
    'login': 'ലോഗിൻ',
    'logout': 'ലോഗ്ഔട്ട്',
    'dashboard': 'ഡാഷ്ബോർഡ്',
    'profile': 'പ്രൊഫൈൽ',
    'settings': 'ക്രമീകരണങ്ങൾ',
    'help': 'സഹായം',
    'chat': 'ചാറ്റ് അസിസ്റ്റന്റ്',
    'voice_assistant': 'വോയ്സ് അസിസ്റ്റന്റ്',
    'language': 'ഭാഷ',
    'accessibility': 'പ്രവേശനക്ഷമത'
  },
  bn: {
    // Common
    'welcome': 'স্বাগতম',
    'login': 'লগইন',
    'logout': 'লগআউট',
    'dashboard': 'ড্যাশবোর্ড',
    'profile': 'প্রোফাইল',
    'settings': 'সেটিংস',
    'help': 'সাহায্য',
    'chat': 'চ্যাট সহায়ক',
    'voice_assistant': 'ভয়েস সহায়ক',
    'language': 'ভাষা',
    'accessibility': 'অ্যাক্সেসিবিলিটি'
  },
  gu: {
    // Common
    'welcome': 'સ્વાગત છે',
    'login': 'લોગિન',
    'logout': 'લોગઆઉટ',
    'dashboard': 'ડેશબોર્ડ',
    'profile': 'પ્રોફાઇલ',
    'settings': 'સેટિંગ્સ',
    'help': 'મદદ',
    'chat': 'ચેટ આસિસ્ટન્ટ',
    'voice_assistant': 'વૉઇસ આસિસ્ટન્ટ',
    'language': 'ભાષા',
    'accessibility': 'પહોંચ'
  },
  mr: {
    // Common
    'welcome': 'स्वागत',
    'login': 'लॉगिन',
    'logout': 'लॉगआउट',
    'dashboard': 'डॅशबोर्ड',
    'profile': 'प्रोफाइल',
    'settings': 'सेटिंग्स',
    'help': 'मदत',
    'chat': 'चॅट असिस्टंट',
    'voice_assistant': 'व्हॉईस असिस्टंट',
    'language': 'भाषा',
    'accessibility': 'प्रवेशयोग्यता'
  },
  pa: {
    // Common
    'welcome': 'ਸੁਆਗਤ ਹੈ',
    'login': 'ਲਾਗਇਨ',
    'logout': 'ਲਾਗਆਉਟ',
    'dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'profile': 'ਪ੍ਰੋਫਾਈਲ',
    'settings': 'ਸੈਟਿੰਗਾਂ',
    'help': 'ਮਦਦ',
    'chat': 'ਚੈਟ ਸਹਾਇਕ',
    'voice_assistant': 'ਆਵਾਜ਼ ਸਹਾਇਕ',
    'language': 'ਭਾਸ਼ਾ',
    'accessibility': 'ਪਹੁੰਚਯੋਗਤਾ'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    try {
      const savedLanguage = localStorage.getItem('sai-language') as Language;
      if (savedLanguage && languages.find(l => l.code === savedLanguage)) {
        setLanguage(savedLanguage);
      }
    } catch (error) {
      console.error('Error loading saved language:', error);
      // Fallback to English if there's an error
      setLanguage('en');
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    try {
      setLanguage(lang);
      localStorage.setItem('sai-language', lang);
    } catch (error) {
      console.error('Error saving language preference:', error);
      // Still update the state even if localStorage fails
      setLanguage(lang);
    }
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage: handleSetLanguage,
      t,
      languages
    }}>
      {children}
    </LanguageContext.Provider>
  );
};